title: Gabriel Cruz
owner: Gabriel Cruz
email: gabriel.melo.cruz@usp.br
description: Gabriel's personal web page
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
language: en

github_url: https://github.com/gmelodie
medium_url: https://medium.com/@gmelodie
linkedin_url: https://www.linkedin.com/in/gabriel-de-melo-cruz/

# Build settings
markdown: kramdown
theme: minima

permalink: /:year/:month/:day/:title/

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle
excerpt_separator: <!--more-->
